apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: domowik

resources:
  - namespace.yaml
  - secrets.yaml
  - postgres/pvc.yaml
  - postgres/deployment.yaml
  - postgres/service.yaml
  - overpass/pvc.yaml
  - overpass/deployment.yaml
  - overpass/service.yaml
  - backend/deployment.yaml
  - backend/service.yaml
  - frontend/deployment.yaml
  - frontend/service.yaml
  - scraper/cronjob.yaml
  - ingress.yaml
