apiVersion: v1
kind: Secret
metadata:
  name: domowik-secrets
  namespace: domowik
type: Opaque
stringData:
  DATABASE_URL: "postgresql+asyncpg://postgres:postgres@postgres:5432/domowik"
  JWT_SECRET: "change-me-in-production"
  SMTP_HOST: "mail.homehero.pro"
  SMTP_USER: "notifications@homehero.pro"
  SMTP_PASS: ""
