apiVersion: v1
kind: Secret
metadata:
  name: domovol-secrets
  namespace: domovol
type: Opaque
stringData:
  DATABASE_URL: "postgresql+asyncpg://postgres:postgres@postgres:5432/domovol"
  JWT_SECRET: "change-me-in-production"
  SMTP_HOST: "mail.homehero.pro"
  SMTP_USER: "notifications@homehero.pro"
  SMTP_PASS: ""
