apiVersion: v1
kind: Secret
metadata:
  name: domowik-secrets
  namespace: domowik
type: Opaque
stringData:
  DATABASE_URL: "postgresql+asyncpg://postgres:postgres@postgres:5432/domowik"
  POSTGRES_PASSWORD: "postgres"
  JWT_SECRET: "lom5hsA0i9979DcqFNn0sX1PwNWdGCJPzgRYONXPAkY="
  SMTP_HOST: ""
  SMTP_USER: ""
  SMTP_PASS: ""
